---
name: "📕 Documentation Issue"
description: Report an issue in the API Reference documentation or Developer Guide
title: "(short issue description)"
labels: [documentation, needs-triage]
assignees: []
body:
  - type: checkboxes
    id: acknowledgments
    attributes:
      label: Acknowledgements
      options:
        - label: This issue submission is for AWS SDK Java v2
        - label: I have looked through the previously submitted documentation issues and confirm that this is not a duplicate submission.
    validations: 
      required: true
  - type: markdown
    attributes:
      value: |
        **What should I do if there already exist a documentation issue submission for this?**

        Any input or additional information is extremely helpful to our team. You can showcase your interest by reacting to the submission with 👍 or share any additional information by commenting on the submission.

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the documentation issue. (Please provide any relevant example of inaccurate/missing documentation)
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: |
        Include links to affected documentation page(s).
    validations:
      required: true
