---
name: 🚀 Feature Request
description: Suggest an idea for this project. This is the place to request any new feature to the SDK that would improve your user experience.
title: "(short issue description)"
labels: [feature-request, needs-triage]
assignees: []
body:
- type: checkboxes
    id: ack
    attributes:
      label: Acknowledgements
      options:
        - label: This issue submission is for AWS SDK Java v2.
        - label: I have looked through the previously submitted feature requests and confirm that this is not a duplicate submission.
          required: true
 - type: markdown
    attributes:
      value: |
        What should I do if there already exist a feature request submission for this?

	Any input or additional information is extremely helpful to our team. You can showcase your interest by reacting to the submission with 👍 or share any additional information by commenting on the submission.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature you are proposing.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Why do you need this feature? How will this improve your user experience? 
    validations:
        required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: |
        Suggest how to implement the addition or change. Please include prototype/workaround/sketch/reference implementation.
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other Information
      description: |
        Any alternative solutions or features you considered, a more detailed explanation, stack traces, related issues, links for context, etc.
    validations:
      required: false
  - type: checkboxes
    id: ack
    attributes:
      label: Acknowledgements
      options:
        - label: I may be able to implement this feature request
          required: false
        - label: This feature might incur a breaking change
          required: false

  - type: input
    id: java-sdk-version
    attributes:
      label: AWS Java SDK version used
    validations:
      required: true

  - type: input
    id: jdk-version
    attributes:
      label: JDK version used
      description: Output of `java -version`
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System and version
    validations:
      required: true
